# fly.toml app configuration file generated for powerappsrudi on 2024-08-07T08:55:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'powerappsrudi'
primary_region = 'mad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  FLET_SESSION_TIMEOUT = '60'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
